Lokators hw
SlavikSavenok/AQA27 pull request #3
Opened 2024-07-11 22:48 UTC by SlavikSavenok

2024-07-15 14:26 UTC, wildpioneer requested changes

2024-07-15 14:26 UTC, wildpioneer commented on src/main/java/services/DriverForTests.java
> +        System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
Ой - а зачем это, если у нас есть WebDriverManager

2024-07-16 10:54 UTC, SlavikSavenok commented on src/main/java/services/DriverForTests.java
> +        System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
удалил лишнее

2024-07-25 13:10 UTC, wildpioneer commented
Проверил

2024-07-25 13:10 UTC, closed without merging