Page object hw
SlavikSavenok/AQA27 pull request #4
Opened 2024-07-24 19:23 UTC by SlavikSavenok

Page object hw

2024-07-25 13:18 UTC, wildpioneer requested changes

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CartPage.java
> +
Форматирование: не надо так много пустых строк - все должно быть одинаково и понятно

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CartPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +    public void clickBackHome(){
Форматирование: отсутствует пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +    public CheckoutComplete(WebDriver driver) {
Форматирование: отсутствует пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutInformationPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutInformationPage.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/CheckoutInformationPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/MenuPage.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/MenuPage.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/pages/MenuPage.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/AddRemoveSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/AddRemoveSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/PaymentSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/PaymentSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/PaymentSteps.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/UserSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/steps/UserSteps.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/test/AddProduct.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/test/PaymentTest.java
> +    @Test
Форматирование: отсутствует пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/test/PaymentTest.java
> +
Форматирование: лишние пустые строки

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/test/RemoveProduct.java
> +    @Test
Форматирование: отсутствует пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/test/RemoveProduct.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/baseEntities/BasePage.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/baseEntities/BaseTest.java
> +
Форматирование: лишняя пустая строка

2024-07-25 13:18 UTC, wildpioneer commented on src/test/java/baseEntities/BaseTest.java
> +
Форматирование: лишние пустые строки

2024-07-25 15:30 UTC, SlavikSavenok commented on src/test/java/pages/CartPage.java
> +
Отформатировал

2024-07-25 15:31 UTC, SlavikSavenok commented on src/test/java/pages/CheckoutComplete.java
> +
Отформатировал

2024-07-25 15:31 UTC, SlavikSavenok commented on src/test/java/pages/CartPage.java
> +
Отформатировал

2024-07-25 15:31 UTC, SlavikSavenok commented on src/test/java/pages/CheckoutComplete.java
> +    public void clickBackHome(){
Отформатировал

2024-07-25 15:31 UTC, SlavikSavenok commented on src/test/java/pages/CheckoutComplete.java
> +    public CheckoutComplete(WebDriver driver) {
Отформатировал

2024-07-25 15:31 UTC, SlavikSavenok commented on src/test/java/test/RemoveProduct.java
> +    @Test
Отформатировал

2024-07-25 15:32 UTC, SlavikSavenok commented on src/test/java/test/RemoveProduct.java
> +
Отформатировал

2024-07-25 15:32 UTC, SlavikSavenok commented on src/test/java/baseEntities/BasePage.java
> +
Отформатировал

2024-07-25 15:32 UTC, SlavikSavenok commented on src/test/java/baseEntities/BaseTest.java
> +
Отформатировал

2024-07-25 15:32 UTC, SlavikSavenok commented on src/test/java/baseEntities/BaseTest.java
> +
Отформатировал

2024-08-20 10:41 UTC, wildpioneer commented
Проверено

2024-08-20 10:41 UTC, closed without merging