Allure hw
SlavikSavenok/AQA27 pull request #6
Opened 2024-08-03 18:37 UTC by SlavikSavenok

Allure hw

2024-08-06 11:10 UTC, wildpioneer requested changes

2024-08-06 11:10 UTC, wildpioneer commented on src/test/resources/allure.properties
> +allure.results.directory=target/allure-results
По Allure замечаний нет - а вот что в репозитории появились файлы из папки .idea - есть

2024-08-10 03:00 UTC, SlavikSavenok commented on src/test/resources/allure.properties
> +allure.results.directory=target/allure-results
Удалил

2024-08-20 10:41 UTC, wildpioneer commented
Проверено

2024-08-20 10:41 UTC, closed without merging